In [27]:
import pandas as pd

In [28]:
distance_matrix = pd.read_csv('AutoIRAD-dataset-distances.csv', index_col=0)
distance_matrix

monks-2.dat  rabe_131.csv  contrac_R.dat  \
monks-2.dat                            0.000000      0.627923       0.455466   
rabe_131.csv                           0.627923      0.000000       0.577918   
contrac_R.dat                          0.455466      0.577918       0.000000   
conn-bench-vowel-deterding.dat         0.092033      0.650764       0.467390   
conn-bench-sonar-mines-rocks_R.dat     1.014555      0.997661       0.814052   
...                                         ...           ...            ...   
schlvote.csv                           0.483285      0.837774       0.593287   
cardiotocography-3clases_R.dat         0.221889      0.680785       0.466447   
car_R.dat                              0.206337      0.627421       0.356352   
pittsburg-bridges-T-OR-D_R.dat         0.340085      0.583447       0.470556   
mfeat-morphological.csv                0.271278      0.747974       0.564495   

                                    conn-bench-vowel-deterding.dat  \
monks-2.dat                                               0.092033   
rabe_131.csv                                              0.650764   
contrac_R.dat                                             0.467390   
conn-bench-vowel-deterding.dat                            0.000000   
conn-bench-sonar-mines-rocks_R.dat                        1.033600   
...                                                            ...   
schlvote.csv                                              0.479333   
cardiotocography-3clases_R.dat                            0.224947   
car_R.dat                                                 0.218815   
pittsburg-bridges-T-OR-D_R.dat                            0.357943   
mfeat-morphological.csv                                   0.262052   

                                    conn-bench-sonar-mines-rocks_R.dat  \
monks-2.dat                                                   1.014555   
rabe_131.csv                                                  0.997661   
contrac_R.dat                                                 0.814052   
conn-bench-vowel-deterding.dat                                1.033600   
conn-bench-sonar-mines-rocks_R.dat                            0.000000   
...                                                                ...   
schlvote.csv                                                  1.093500   
cardiotocography-3clases_R.dat                                0.969117   
car_R.dat                                                     0.960254   
pittsburg-bridges-T-OR-D_R.dat                                0.978013   
mfeat-morphological.csv                                       1.012198   

                                    hepatitis_R.dat  low-res-spect_R.dat  \
monks-2.dat                                0.379417             0.193740   
rabe_131.csv                               0.523115             0.595663   
contrac_R.dat                              0.406350             0.511681   
conn-bench-vowel-deterding.dat             0.426256             0.212445   
conn-bench-sonar-mines-rocks_R.dat         0.975751             1.042188   
...                                             ...                  ...   
schlvote.csv                               0.574874             0.539357   
cardiotocography-3clases_R.dat             0.518411             0.300497   
car_R.dat                                  0.329267             0.286047   
pittsburg-bridges-T-OR-D_R.dat             0.334432             0.364612   
mfeat-morphological.csv                    0.495786             0.345352   

                                    cardiotocography-10clases_R.dat  \
monks-2.dat                                                0.329588   
rabe_131.csv                                               0.626955   
contrac_R.dat                                              0.353217   
conn-bench-vowel-deterding.dat                             0.342974   
conn-bench-sonar-mines-rocks_R.dat                         0.863258   
...   

### K-Medoids

In [29]:
from sklearn_extra.cluster import KMedoids

clustering = KMedoids(n_clusters=9, metric='precomputed')
labels = clustering.fit_predict(distance_matrix)
labels

array([5, 0, 4, 5, 3, 5, 5, 1, 2, 2, 3, 8, 8, 1, 5, 5, 4, 5, 5, 8, 4, 6,
       8, 4, 4, 4, 5, 5, 5, 5, 3, 8, 5, 2, 5, 4, 1, 6, 4, 8, 5, 1, 2, 5,
       4, 5, 5, 5, 0, 2, 8, 5, 6, 6, 8, 2, 0, 6, 8, 4, 3, 3, 5, 3, 8, 4,
       8, 6, 2, 5, 5, 6, 3, 5, 5, 1, 5, 2, 3, 8, 8, 6, 5, 5, 3, 3, 5, 4,
       5, 6, 5, 4, 2, 6, 1, 3, 1, 8, 8, 2, 5, 3, 7, 4, 4, 3, 8, 5, 2, 8,
       0, 1, 7, 4, 3, 8, 5, 5, 5, 8, 0, 5, 6, 5, 6, 1, 6, 5, 5])

In [30]:
for i in range(9):
    print(f'Cluster {i}:')
    print(distance_matrix.index[labels == i])

Cluster 0:
Index(['rabe_131.csv', 'energy-y1_R.dat', 'image-segmentation.dat',
       'audiology-std.dat', 'energy-y2_R.dat'],
      dtype='object')
Cluster 1:
Index(['cardiotocography-10clases_R.dat', 'ionosphere_R.dat', 'spectf.dat',
       'yeast_R.dat', 'breast-cancer-wisc-diag_R.dat', 'dermatology_R.dat',
       'pittsburg-bridges-SPAN_R.dat', 'breast-cancer-wisc_R.dat',
       'cardiotocography-3clases_R.dat'],
      dtype='object')
Cluster 2:
Index(['acute-nephritis.dat', 'pittsburg-bridges-TYPE_R.dat',
       'heart-hungarian_R.dat', 'vertebral-column-2clases_R.dat',
       'vertebral-column-3clases_R.dat', 'glass_R.dat', 'breast-cancer_R.dat',
       'wine_R.dat', 'seeds_R.dat', 'iris_R.dat', 'tic-tac-toe_R.dat'],
      dtype='object')
Cluster 3:
Index(['conn-bench-sonar-mines-rocks_R.dat', 'plant-margin_R.dat',
       'synthetic-control_R.dat', 'plant-texture_R.dat', 'libras_R.dat',
       'plant-shape_R.dat', 'molec-biol-splice_R.dat', 'musk-1_R.dat',
       'steel-plates_R.

### AHC

In [31]:
from sklearn.cluster import AgglomerativeClustering

clustering = AgglomerativeClustering(
    n_clusters=9, metric='precomputed', linkage='complete')
labels = clustering.fit_predict(distance_matrix)
labels

array([8, 1, 2, 8, 2, 8, 8, 8, 2, 2, 2, 3, 3, 8, 8, 8, 1, 8, 8, 1, 7, 8,
       1, 3, 8, 1, 8, 8, 8, 8, 2, 1, 8, 2, 8, 8, 8, 8, 7, 3, 8, 8, 2, 8,
       7, 8, 8, 8, 8, 2, 5, 8, 8, 8, 0, 2, 8, 8, 3, 8, 2, 2, 8, 2, 3, 8,
       6, 8, 2, 8, 8, 8, 2, 8, 8, 8, 8, 2, 2, 4, 3, 8, 8, 8, 2, 2, 8, 8,
       8, 8, 8, 8, 2, 8, 8, 2, 8, 3, 8, 2, 8, 2, 8, 7, 2, 2, 0, 8, 2, 1,
       8, 8, 8, 8, 2, 1, 8, 8, 8, 3, 8, 8, 8, 8, 8, 8, 8, 8, 8])

In [32]:
for i in range(9):
    print(f'Cluster {i}:')
    print(distance_matrix.index[labels == i])

Cluster 0:
Index(['fri_c0_250_5.csv', 'triazines.csv'], dtype='object')
Cluster 1:
Index(['rabe_131.csv', 'lupus.csv', 'sleuth_case2002.csv', 'chatfield_4.csv',
       'diggle_table_a2.csv', 'chscase_vine1.csv', 'transplant.csv',
       'bodyfat.csv'],
      dtype='object')
Cluster 2:
Index(['contrac_R.dat', 'conn-bench-sonar-mines-rocks_R.dat',
       'acute-nephritis.dat', 'pittsburg-bridges-TYPE_R.dat',
       'plant-margin_R.dat', 'synthetic-control_R.dat',
       'heart-hungarian_R.dat', 'vertebral-column-2clases_R.dat',
       'vertebral-column-3clases_R.dat', 'glass_R.dat', 'plant-texture_R.dat',
       'libras_R.dat', 'plant-shape_R.dat', 'breast-cancer_R.dat',
       'molec-biol-splice_R.dat', 'wine_R.dat', 'musk-1_R.dat',
       'steel-plates_R.dat', 'ecoli_R.dat', 'seeds_R.dat', 'spambase_R.dat',
       'iris_R.dat', 'molec-biol-promoter_R.dat', 'mushroom_R.dat',
       'elusage.csv', 'tic-tac-toe_R.dat', 'breast-tissue_R.dat'],
      dtype='object')
Cluster 3:
Index(['teach

### DBSCAN

In [33]:
from sklearn.cluster import DBSCAN

clustering = DBSCAN(eps=0.5, min_samples=2, metric='precomputed')
labels = clustering.fit_predict(distance_matrix)
labels

array([ 0, -1,  0,  0,  0,  0,  0,  0,  0,  0,  0,  1,  2,  0,  0,  0,  0,
        0,  0, -1,  3,  0, -1,  0,  0, -1,  0,  0,  0,  0,  0, -1,  0,  0,
        0,  0,  0,  0,  3,  0,  0,  0,  0,  0,  3,  0,  0,  0,  0,  0, -1,
        0,  0,  0, -1,  0, -1,  0,  2,  0,  0,  0,  0,  0,  2,  0, -1,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, -1,  4,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  4,  0,  0,  0,  0,
        0,  3,  0,  0, -1,  0,  0, -1,  0,  0,  0,  0,  0, -1,  0,  0,  0,
        1,  0,  0,  0,  0,  0,  0,  0,  0,  0])

In [34]:
for i in range(9):
    print(f'Cluster {i}:')
    print(distance_matrix.index[labels == i])

Cluster 0:
Index(['monks-2.dat', 'contrac_R.dat', 'conn-bench-vowel-deterding.dat',
       'conn-bench-sonar-mines-rocks_R.dat', 'hepatitis_R.dat',
       'low-res-spect_R.dat', 'cardiotocography-10clases_R.dat',
       'acute-nephritis.dat', 'pittsburg-bridges-TYPE_R.dat',
       'plant-margin_R.dat',
       ...
       'oocytes_merluccius_states_2f_R.dat', 'energy-y2_R.dat', 'spect.dat',
       'soybean.dat', 'post-operative_R.dat', 'schlvote.csv',
       'cardiotocography-3clases_R.dat', 'car_R.dat',
       'pittsburg-bridges-T-OR-D_R.dat', 'mfeat-morphological.csv'],
      dtype='object', length=105)
Cluster 1:
Index(['teachingAssistant.csv', 'tae.csv'], dtype='object')
Cluster 2:
Index(['analcatdata_lawsuit.csv', 'disclosure_z.csv', 'diabetes.csv'], dtype='object')
Cluster 3:
Index(['horse-colic.dat', 'hill-valley.dat', 'ar4.csv', 'kc3.csv'], dtype='object')
Cluster 4:
Index(['prnn_synth.csv', 'veteran.csv'], dtype='object')
Cluster 5:
Index([], dtype='object')
Cluster 6:
Index([],